# Generated by Django 4.2.4 on 2023-09-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specialities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Speciality", models.CharField(max_length=400)),
                ("Specialities", models.CharField(max_length=400)),
                ("Nnpoa", models.IntegerField(blank=True, null=True)),
                ("NC", models.IntegerField(blank=True, null=True)),
                ("CF", models.FloatField(blank=True, null=True)),
                ("Tlcnumber", models.IntegerField(blank=True, null=True)),
                ("Tlcf", models.FloatField(blank=True, null=True)),
                ("HvfNumber", models.IntegerField(blank=True, null=True)),
                ("Hvf", models.FloatField(blank=True, null=True)),
                ("HvfAvrage", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
